article/urls.py
from django.urls import path

from article.views import (
    article_create_view,
    article_detail_view,
    article_search_view,
)

app_name = 'article'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),
]

tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
    login_view,
    logout_view,
    register_view,
)

from search.views import search_view
from .views import home_view

# int:id needs to be last, because it has datatype int.
# otherwise keep in alphabetical order
urlpatterns = [
    path('', home_view),
    path('recipes/', include('recipes.urls')),
    path('articles/', include('article.urls')),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.5.0"></script>
    <style>
        .htmx-indicator {
            display: none;
        }

        .htmx-request .htmx-indicator {
            display: inline;
        }
        .htmx-inverted-indicator {
            display: inline;
        }
        .htmx-request .htmx-inverted-indicator {
            display: none;
        }

    </style>
    <title>Django Tutorial</title>
</head>

<body>
    <h1>Django Tutorial</h1>
    {% include 'search/search-form.html' %}
    <div>
        {% block content %}

        {% endblock content%}
    </div>

    <script>
        document.body.addEventListener("htmx:configRequest", (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
        })
    </script>
</body>

</html>

templates/home-view.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ object.title }} (id{{ id }})</h1>
<p>{{ content }}</p>

<a href="{% url 'article:create' %}">Create Article</a>
<ul>
    {% for x in object_list %}
        {% if x.title %}
            <li><a href="{{ x.get_absolute_url }}">{{ x.title }} - {{ x.content }}</li></a>
        {% endif %}
    {% endfor %}
</ul>

{% endblock content %}